### ISSUE TITLE
Impossibility of removal of private datasets for quota limits

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL-WEB#60]
@andreagulino 
Some users (Kia) experienced on genomic the not decreasing storage occupancy although after deleting all their datasets; this occurred when the user stopped a running job (probably after reaching the quota limit), which made many "gost" files to remain in her disk space, but not visible in the web interface and thus not removable (Arif had to delete them manually). 

Another users (Gaia) experienced on Cineca the impossibility of deleting datasets from her space, with the impossibility to reduce her quota occupancy (you deleted them manually) 
Can you please check and fix the issue, avoiding it reappear?

**Comment by andreagulino** [comment]
With Arif we changed the code so to prevent that when a user deletes a dataset it still remains on the HDFS.

**Comment by marcomass** [comment]
Unfortunately I reopen this issue since it seems the problem is not solved

**Comment by acanakoglu** [comment]
@akaitoua , could you please check the situation of the stop button stopping the execution?

**Comment by andreagulino** [comment]
With @acanakoglu we solved the problem. The solution includes:
- Correctly stopping Spark execution through an additional call to the SparkHandler 
- Removing residual datasets when the job is killed (or fails)
- Computing the space occupied by the user by summing the size of each dataset shown in the web ui (rather than asking Hadoop for the size of the region folder)
